#!/bin/bash
# push_blog_to_server.sh
# diphia@2019
# This script is used to push the local static web pages to the server, the IP address and file location should be set before. After pushing, script will create a log automatically.

remote_username="ubuntu"
remote_ip="49.234.63.85"
remote_location="~/"
hugo_location="/home/diphia/Westfall"

if [ ! -f "${hugo_location}/push_history.log" ]
then
	touch ${hugo_location}/push_history.log
	echo "(1/3) no push_history detected, new file created"
	echo -e "This Logfile is generated by the script push_blog_to_server \n--------------------" >> ${hugo_location}/push_history.log
else
	cp ${hugo_location}/push_history.log ${hugo_location}/push_history.log.bak
	echo "(1/3) push_history detected, backup file created"
	echo -e "--------------------\npush_history backed @ `date`" >> ${hugo_location}/push_history.log.bak
fi

echo -e "\n\n--------------------\nDate:`date`\n\nHugo\n" >> ${hugo_location}/push_history.log

cd ${hugo_location}
echo "Generating the static site with Hugo......"
hugo | sed '1d' >> ${hugo_location}/push_history.log # delete the first line which shows "Building sites ..."
echo "(2/3) Static site generated"

echo -e "\nRsync:" >> ${hugo_location}/push_history.log
echo "Syncing files with Rsync......"
rsync -avz -e'ssh -p 22' ${hugo_location}/public ${remote_username}@${remote_ip}:${remote_location} | tail -n 2 >> ${hugo_location}/push_history.log
echo "------------------------------------" >> ${hugo_location}/push_history.log
echo -e "(3/3) All files synced to ${remote_ip}\nDone!"
